# Generated by Django 5.2.6 on 2025-09-11 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="movie_genre",
            new_name="genres",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="year",
        ),
        migrations.AddField(
            model_name="movie",
            name="release_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="age_restriction",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="moviefile",
            name="file",
            field=models.FileField(upload_to="movies/videos"),
        ),
        migrations.AlterField(
            model_name="moviefile",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
            ),
        ),
        migrations.AlterField(
            model_name="posterimage",
            name="image",
            field=models.ImageField(upload_to="movies/posters/"),
        ),
        migrations.AlterField(
            model_name="posterimage",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
            ),
        ),
    ]
