# Generated by Django 5.2.6 on 2025-09-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_genre_name_alter_language_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviefile",
            name="quality",
            field=models.CharField(
                choices=[("480p", "480p"), ("720p", "720p"), ("1080p", "1080p")],
                default="720p",
                max_length=20,
            ),
        ),
    ]
