# Generated by Django 5.2.6 on 2025-09-16 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_moviefile_quality"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("MOBILE", "Mobile"),
                            ("TABLET", "Tablet"),
                            ("PC", "PC"),
                            ("SMARTTV", "SmartTV"),
                        ],
                        default="Mobile",
                        max_length=20,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("480p", "480p"),
                            ("720p", "720p"),
                            ("1080p", "1080p"),
                        ],
                        default="720p",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.country"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.language",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "subtitle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.moviesubtitle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
