# Generated by Django 5.2.6 on 2025-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_watchsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviefile",
            name="quality",
            field=models.CharField(
                choices=[
                    ("360p", "360p"),
                    ("480p", "480p"),
                    ("720p", "720p"),
                    ("1080p", "1080p"),
                    ("4K", "4K"),
                ],
                default="720p",
            ),
        ),
        migrations.DeleteModel(
            name="WatchSession",
        ),
    ]
